# Generated by Django 3.1.3 on 2020-11-05 14:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NewUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('date_joined', models.DateTimeField(auto_now_add=True, verbose_name='date joined')),
                ('last_login', models.DateTimeField(auto_now_add=True, verbose_name='last seen')),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_admin', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('newuser_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='better_therapy.newuser')),
                ('f_name', models.CharField(max_length=30, verbose_name='first name')),
                ('l_name', models.CharField(max_length=30, verbose_name='last name')),
                ('ph_num', models.CharField(max_length=10, verbose_name='phone number')),
            ],
            options={
                'abstract': False,
            },
            bases=('better_therapy.newuser',),
        ),
        migrations.CreateModel(
            name='Therapist',
            fields=[
                ('client_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='better_therapy.client')),
                ('is_therapist', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('better_therapy.client',),
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('therapist_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='better_therapy.therapist')),
                ('is_supervisor', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('better_therapy.therapist',),
        ),
    ]
