# Generated by Django 3.1.3 on 2020-11-05 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('better_therapy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='newuser',
            name='is_test',
            field=models.BooleanField(default=True),
        ),
    ]
