# Generated by Django 3.1.3 on 2020-11-05 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('better_therapy', '0002_newuser_is_test'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newuser',
            name='is_test',
        ),
    ]
